### ISSUE TITLE
1 and 0 ?

### ISSUE THREAD

**Issue by cirocosta** [sindresorhus/yn#2]
What about 1/0 ? :neckbeard:

**Comment by markstos** [comment]
I'm also interested in 1/0 support and have a use case. 

I'm considering using this module for handling CSV input, where I'll be getting a range of values out of my control including "TRUE", "FALSE" as well as possibly "1" and "0". (For that matter, possibly "t" and "f" as well, but those haven't come up yet in my own datasets). 

1 and 0 are common representations of booleans when databases export tables to CSV format.

**Comment by markstos** [comment]
Since it doesn't like `yn` is going to get support for "1" and "0", folks looking for it can use the `to-boolean` package instead, which has similar functionality but also supports "1" and "0" for true and false values:

https://www.npmjs.com/package/to-boolean
https://github.com/rafaelrinaldi/to-boolean

**Comment by sindresorhus** [comment]
PR welcome.
